version: "3.3"

services:
  pgsql:
    restart: unless-stopped
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=contacts-app

volumes:
  data:
    driver: local
